export { default as iPlay } from './iPlay.vue'
export { default as iLoop } from './iLoop.vue'
export { default as iLamp } from './iLamp.vue'
export { default as iStation } from './iStation.vue'
export { default as iSpin } from './iSpin.vue'
export { default as iSound } from './iSound.vue'
